apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-staging
  labels:
    app: flask-app
    env: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
      env: staging
  template:
    metadata:
      labels:
        app: flask-app
        env: staging
    spec:
      containers:
      - name: flask-app
        image: kikyputraa/devops-playground:d305254383e87f5d7cfd6fa40d522a2f9f181045
        ports:
        - containerPort: 5000