apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-staging
  labels:
    app: flask-app
    env: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
      env: staging
  template:
    metadata:
      labels:
        app: flask-app
        env: staging
    spec:
      containers:
      - name: flask-app
        image: kikyputraa/devops-playground:95cab77f2b39f15bed8ac0998d5c511b2b9bb7a0
        ports:
        - containerPort: 5000