name: DevSecOps Pipeline

on:
  push:
    branches: [ "main", "staging" ]
    paths-ignore:
      - 'k8s/**'
      - 'README.md'

jobs:
  sast_bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install bandit && bandit -r app/ -ll

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install pytest pytest-cov Flask
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest --cov=app --cov-report=xml:coverage.xml tests/
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  sonarqube_check:
    needs: [unit_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: coverage-report
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_image:
    needs: [sonarqube_check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker build -t kikyputraa/devops-playground:${{ github.sha }} .
          docker save kikyputraa/devops-playground:${{ github.sha }} > app_image.tar
      - uses: actions/upload-artifact@v4
        with:
          name: docker-artifact
          path: app_image.tar

  container_security:
    needs: [build_image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-artifact
      - uses: aquasecurity/trivy-action@master
        with:
          input: 'app_image.tar'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true

  push_image:
    needs: [container_security]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-artifact
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker load < app_image.tar
          docker push kikyputraa/devops-playground:${{ github.sha }}
          docker tag kikyputraa/devops-playground:${{ github.sha }} kikyputraa/devops-playground:latest
          docker push kikyputraa/devops-playground:latest

  deploy_gitops:
    needs: [push_image]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update Manifests
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TARGET_DIR="k8s/prod"
          else
            TARGET_DIR="k8s/staging"
          fi
          # Update to latest and set Always pull policy
          sed -i "s|image: .*|image: kikyputraa/devops-playground:latest|g" $TARGET_DIR/deployment.yaml
          if ! grep -q "imagePullPolicy: Always" $TARGET_DIR/deployment.yaml; then
            sed -i "/image: .*/a \        imagePullPolicy: Always" $TARGET_DIR/deployment.yaml
          fi

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "chore: update manifests to latest with Always pull policy"
            git push
          fi